export default function handler(req, res) {
  const lines = [
    "🚨 VIEWER ADVISORY: Guest commentary reflects individual opinions and should not be attributed to the streamer, moderation team, or anyone who has ever conducted basic research. 🚨",

    "🚨 DISCLAIMER: Statements made by guests are their own and do not necessarily reflect the views of the streamer, moderators, sponsors, or the English language itself. 🚨",

    "🚨 NOTICE TO VIEWERS: Any comments that sound suspicious when repeated out loud remain the sole responsibility of the speaker. 🚨",

    "🚨 COMMUNITY DISCLAIMER: Opinions expressed by guests have not been reviewed, verified, fact-checked, or sanity-checked by stream management. 🚨",

    "🚨 LEGAL NOTICE: The streamer assumes no responsibility for remarks that immediately cause chat to type 'AYO.' 🚨",

    "🚨 VIEWER CAUTION: Guest commentary may contain excessive confidence, limited evidence, and unintended implications. 🚨",

    "🚨 BROADCAST DISCLAIMER: Statements made during this program do not represent the streamer, moderators, or anyone who thought about the wording for more than three seconds. 🚨",

    "🚨 PUBLIC NOTICE: Any resemblance between guest commentary and carefully considered opinions is purely coincidental. 🚨",

    "🚨 DISCLOSURE: Guests speak solely on their own behalf and not on behalf of the streamer, moderation team, legal counsel, or human resources. 🚨",

    "🚨 ADVISORY: Comments made by guests may be clipped, replayed, and presented as evidence in the Court of Public Chat. 🚨",

    "🚨 DISCLAIMER: Stream management cannot be held liable for statements that become significantly worse when taken in context. 🚨",

    "🚨 VIEWER NOTICE: Guest commentary may contain traces of speculation, overconfidence, and accidental self-reporting. 🚨",

    "🚨 LEGAL DISCLAIMER: The opinions expressed herein have not been approved by experts, professionals, or anyone present in this channel. 🚨",

    "🚨 BROADCAST NOTICE: Any statement requiring the phrase 'that's not what I meant' remains the sole responsibility of the speaker. 🚨",

    "🚨 ADVISORY TO CHAT: The streamer and moderation team reserve the right to laugh at any comment that sounds far more questionable than intended. 🚨",

    "🚨 DISCLOSURE STATEMENT: Guest commentary may include wording choices that no reasonable advisor would have recommended. 🚨",

    "🚨 NOTICE: Statements expressed by guests are independent opinions and not endorsements by the streamer, moderators, or common sense. 🚨",

    "🚨 VIEWER WARNING: Certain remarks may produce side effects including confusion, secondhand embarrassment, and requests for clarification. 🚨",

    "🚨 DISCLAIMER: Any accidental allegations generated by a guest's choice of words are the property of the guest and the guest alone. 🚨",

    "🚨 OFFICIAL NOTICE: Stream management acknowledges hearing the statement and wishes to be excluded from further discussion. 🚨"
  ];

  const random = lines[Math.floor(Math.random() * lines.length)];
  res.status(200).send(random);
}
