export default function handler(req, res) {
  const lines = [
    "is lurkin’ in the shadows like a possum in a whiskey barrel.",
    "just said 'Don’t mind me, I’m just lurkin’ like a bounty in the tall grass.'",
    "is takin’ a break, watchin’ y’all from the saddle with some canned beans.",
    "is lurkin’ under Dutch’s tent… probably lookin’ for snacks.",
    "said they’re lurkin’ — but we all saw them ride into a tree.",
    "is keepin’ it low like a wanted poster with the corners ripped off.",
    "is goin' full stealth — even the raccoons can’t hear 'em lurk.",
    "lurkin’ like a cowpoke who owes the saloon tab and ain’t tryna pay.",
    "just whispered ‘I’m lurkin’, partner’ and disappeared into a haystack.",
    "is gone ghost like Arthur during chores time.",
    "is lurkin’ like a bounty hunter behind a barrel — quiet, but still watchin’.",
    "just left a note: 'Gone lurkin’. Don’t send Micah.'",
    "is lurkin’ like they just failed a stealth mission… again.",
    "slipped out the back with a cigar, a flask, and some heavy lurk energy.",
    "said 'I’ll be lurkin’' — we all heard it. Loudly.",
    "is peepin’ from the outhouse window. Weird, but okay.",
    "is on lurk patrol — likely with a cup of coffee and bad intentions.",
    "is lurkin’ so hard even Dutch can’t find 'em.",
    "rode off sayin’ 'I’m lurkin’ — don’t wait up, cowboy.'",
    "just ducked behind the saloon and said ‘y’all got this.’",
    "said they’re lurkin’ — but they’re really just nappin’ by the campfire.",
    "is lurkin’ like Sadie on a bounty job — eyes sharp, mouth shut.",
    "is lurkin’ in cinematic mode and missed their turn. Twice.",
    "snuck off with Pearson’s stew and a plan to lurk indefinitely.",
    "just vanished like Arthur’s journal entries on a rainy day.",
    "left camp mumbling something about ‘Dutch’s plan’ and a fishing rod.",
    "is behind the wagon, lurkin’ with a harmonica and a questionable snack.",
    "just dipped out whispering 'I got things to not do.'",
    "is lurkin’ under the stars with a can of beans and no regrets.",
    "tried to lurk… tripped over a chicken.",
    "is pretendin’ to be busy so they can lurk guilt-free.",
    "rode out at dawn, said they’d be lurkin’ till sundown.",
    "is lurkin’ like Uncle during firewood duty.",
    "is just off-screen, probably spying from the tree line.",
    "said ‘be right back’ then got distracted by a moose.",
    "hid behind the general store and hasn't moved in 10 minutes.",
    "claimed it’s a tactical lurk. We believe them... kind of.",
    "said they were goin’ on a spiritual lurk journey.",
    "is lurkin’ like Dutch owes 'em money — intense but subtle.",
    "is napping in the hayloft. Lurk level: expert.",
    "just stepped out with a sandwich and the spirit of a drifter.",
    "is leanin’ on a fence, starin’ dramatically into the lurk distance.",
    "started lurkin’ then wandered off muttering about pelts.",
    "lurkin’ with a poker face so good even Hosea’s impressed.",
    "is off the map — probably livin’ that peak lurk life.",
    "is lurkin’ from the back of a runaway wagon. Yeehaw.",
    "wrote ‘AFK’ in the dirt with a stick and disappeared.",
    "is takin’ a break from shootouts to lurk in peace.",
    "snuck off with the last biscuit. Bold lurk energy.",
    "is lurkin’ harder than Dutch is plannin’."
  ];

  const random = lines[Math.floor(Math.random() * lines.length)];
  res.status(200).send(random);
}
