export default function handler(req, res) {
  const lines = [
    "Giggity giggity goo! — Quagmire",
    "Roadhouse. — Peter",
    "Victory is mine! — Stewie",
    "What the deuce? — Stewie",
    "Shut up, Meg. — Peter",
    "Whose leg do you gotta hump to get a dry martini around here? — Brian",
    "Holy crap! — Peter",
    "Oh no! Oh no! Oh no! OH YEAH! — Kool-Aid Man",
    "You mock me, woman! — Stewie",
    "Damn you, vile woman! — Stewie",
    "Lois, Lois, Lois, Mom, Mommy, Mama... — Stewie",
    "I'm an individual, Lois. Just like everybody else. — Peter",
    "I have an idea so smart that my head would explode if I even began to know what I was talking about. — Peter",
    "Peanut butter jelly time! — Brian",
    "No, no, no, no, no, noaaaa! — Cleveland",
    "Over. — Peter (on walkie-talkie)",
    "Perhaps I can interest you in a component system? — Mort Goldman",
    "Hey, Peter, I can see your house from here! — Quagmire",
    "Say 'cool whip'. — Brian",
    "I'm not a pervert, I'm an explorer. — Quagmire",
    "Evil Monkey in my closet! — Chris",
    "Who wants chowder? — Peter",
    "A boat's a boat, but the mystery box could be anything! It could even be a boat! — Peter",
    "Pea... tear... gryphon. Yeah, Peter Griffin! — Peter",
    "Surfin' Bird! — Peter",
    "Don't you know about the bird? — Peter",
    "Everybody knows that the bird is the word! — Peter",
    "I'm a tumor, I'm a tumor, I'm a tumor... — Peter",
    "To the Petercopter! — Peter",
    "To the Hindenpeter! — Peter",
    "You're a big fat phony! — Phony Guy",
    "Hey, everyone! Look at the phony! — Phony Guy",
    "Where's my money? — Stewie",
    "You got money for fake mustaches but you don't got my money? — Stewie",
    "Assahola-miah! — Peter",
    "My name is Consuela. — Consuela",
    "No... no... Superman no home. — Consuela",
    "Need more Lemon Pledge. — Consuela",
    "I can't feel my legs! — Joe",
    "There's a giant chicken outside! — Peter",
    "I'm gonna go do some sweet jumps. — Chris",
    "A-well-a everybody's heard about the bird! — Peter",
    "I have stolen the fire from the sun! — Mayor West",
    "How the hell do you spell 'FBI'? — Peter",
    "Whoa, whoa, whoa, whoa, whoa... Lois, this is not my Batman glass. — Peter",
    "Now I may be an idiot, but there's one thing I am not sir, and that sir, is an idiot. — Peter",
    "Lois, it's 4:00 in the morning. Time for breakfast! — Peter",
    "By the power of Grayskull... I HAVE NO PANTS! — Peter",
    "Giggity giggity crabbity giggity! — Quagmire",
    "I am Petoria! — Peter",
    "I am the mayor of Quahog, and I do what I want. — Mayor West",
    "You better watch who you're calling a child, Lois. Because if I'm a child, you know what that makes you? A pedophile! And I'll be damned if I'm gonna stand here and be lectured by a pervert! — Peter",
    "Brian! Look! There's a message in my alphabits! It says 'oooooo'! ... Peter, those are cheerios. — Peter & Brian",
    "It insists upon itself. — Peter (on The Godfather)",
    "I find this meatloaf rather shallow and pedantic. — Peter",
    "Lois, I'm not drunk, I'm just exhausted because I stayed up all night drinking. — Peter",
    "How much signal I need to cut across 8 lane? None? I turn now. Good luck, everybody else! — Asian Driver cutaway",
    "BUTTSCRATCHER?! BUTTSCRATCHER! — Peter",
    "Does this sideboob turn you on? Well it shouldn't, because that's my sideboob. — Peter",
    "Who the hell starts a conversation like that?! I just sat down! — Random guy in bar",
    "Mr. Weed, I cannot come into work today. I was in a terrible plane crash. My entire family was killed and I am a vegetable... I'll see you tomorrow. — Peter",
    "Oh no, Lois. A guy I know bought a car out of the paper once. 10 years later, BAM. Herpes!! — Peter",
    "WHY ARE WE NOT FUNDING THIS?! — Peter",
    "It's a jackal! A jackal? Jackal! It's a jackal! — Stewie",
    "I always thought that dogs, ummm, laid eggs. And I learned something today. — Peter",
    "You're all so ugly, if this was an ugly contest you'd all win... or lose, whichever's funnier. — Wilkins Hyundai Spokesman",
    "Carter: LOSER! Peter: What? Carter: I said you're a loser! Peter: WHO IS THIS? — Carter & Peter",
    "Time's a factor, Lois!!! — Peter",
    "I want to show my kids what it looks like when a bitch dies!!!! — Peter",
    "BONNIE! YOU LIED TO ME ABOUT THE POOP SACK! — Joe",
    "Lois! It is called the poop deck! That is why I pooped there! — Peter",
    "Excuse me, where did you find crack? ... I got it from Blacks. Yeah, there's a white guy behind Blacks Hardware sellin' it. — Brian & Peter",
    "I'm no meteorologist, but I think it's raining bitches! — Peter",
    "What is a penguin, some kind-uh bug? — Peter",
    "Because you touch yourself at night. — Abraham Lincoln",
    "Damn nature, you scary! — Cutaway Narrator",
    "Oh crap, you smell that? That's brain smell. — Peter",
    "Oh my god, WHO THE HELL CARES? — Peter",
    "You know what else lasts eternity? This conversation. — Peter",
    "Every time I see a sign that says 'SLOW CHILDREN' I say 'Fast Animals / Slow Children'. — Brian",
    "I'm gonna find a black neighborhood and say the you-know-what word... [cuts] ...They respected me for saying it. — Peter",
    "Meg, who let you back in the house? — Peter",
    "Shave a man's back and he'll purr like a walrus. — Peter",
    "Hey, Copernicus! Why don't you navigate yourself to the back of the line with your feet, and stand there with your shirt? — Peter",
    "Lois: Joe, I can't hold you! You're too heavy! Joe: Lois! Pretend I'm one of your children! [Lois drops him] Joe: Not Meg! — Lois & Joe",
    "If I'm fat, then Stewie's fat too because we wear the same size onesie. — Peter",
    "Brian had sex with a really dumb girl, and he's taking his friend Stewie to get some ice cream in his ca-har! — Stewie (singing)",
    "Go get Mom!! — Chris",
    "Mmm... that's right, Shia. Give me all you've got. — Stewie (in the sprinklers)",
    "Why wouldn't you look at me during? — Peter (to a rhino)",
    "Take it up with my butt, because he's the only one that gives a crap. — Peter",
    "Hey, baby. How would you like to go black, and then make a difficult decision regarding whether or not to go back? — Peter",
    "You're a fart smeller, Meg. — Peter",
    "It's the right episode, but the girl ODs so they didn't kill her. — Contextual Nerd",
    "Look at me, I'm gross! — Peter",
    "This is like that time I went to the prom with a giant piece of cheese. — Peter",
    "Stop everything! I have found a penny! — Peter",
    "Lois, look! I'm a beautiful butterfly! — Peter",
    "I took a calculated risk, but man, am I bad at math. — Peter",
    "You're turning violet, Violet! — Peter"
  ];

  const random = lines[Math.floor(Math.random() * lines.length)];
  res.status(200).send(random);
}
