export default function handler(req, res) {
  const lines = [
    "Giggity giggity goo! — Quagmire",
    "Roadhouse. — Peter",
    "Victory is mine! — Stewie",
    "What the deuce? — Stewie",
    "Shut up, Meg. — Peter",
    "Hi, I'm Tom Tucker, and I'm Diane Simmons. — Tom Tucker",
    "Whose leg do you gotta hump to get a dry martini around here? — Brian",
    "Holy crap! — Peter",
    "Oh no! Oh no! Oh no! OH YEAH! — Kool-Aid Man",
    "You mock me, woman! — Stewie",
    "Damn you, vile woman! — Stewie",
    "Lois, Lois, Lois, Mom, Mommy, Mama... — Stewie",
    "I'm an individual, Lois. Just like everybody else. — Peter",
    "I have an idea so smart that my head would explode if I even began to know what I was talking about. — Peter",
    "Peanut butter jelly time! — Brian",
    "No, no, no, no, no, noaaaa! — Cleveland",
    "Over. — Peter (on walkie-talkie)",
    "Perhaps I can interest you in a component system? — Mort Goldman",
    "Take your stinkin' paws off me, you damn dirty ape! — Stewie",
    "Hey, Peter, I can see your house from here! — Quagmire",
    "I am the man who grabs life by the horns and... gets them lodged in his eye socket. — Peter",
    "You know, Peter, you're a real class act. — Brian",
    "I state my regret. — Brian",
    "How dynamic. — Stewie",
    "Go on, structural deficit! — Peter",
    "Say 'cool whip'. — Brian",
    "I'm not a pervert, I'm an explorer. — Quagmire",
    "It's a look. — Peter",
    "Why do we have to play your game? — Chris",
    "Evil Monkey in my closet! — Chris",
    "Who wants chowder? — Peter",
    "I laugh at the concept of your authority. — Stewie",
    "By the power of Grayskull! — Peter",
    "Look at me, I'm a CGI monster! — Peter",
    "That is so fetch. — Peter",
    "A boat's a boat, but the mystery box could be anything! It could even be a boat! — Peter",
    "I can be un-paralyzed? — Joe",
    "Let's go to the Drunken Clam. — Peter",
    "Pea... tear... gryphon. Yeah, Peter Griffin! — Peter",
    "You look like a giant Smurf. — Peter",
    "This is the worst thing that's ever happened to me. Except for that one time... — Peter",
    "Surfin' Bird! — Peter",
    "Don't you know about the bird? — Peter",
    "Everybody knows that the bird is the word! — Peter",
    "This is my sexy party. — Peter",
    "Oh, I hate you so much. — Lois",
    "That is wicked awesome. — Peter",
    "I'm a tumor, I'm a tumor, I'm a tumor... — Peter",
    "You can't handle the truth! — Peter",
    "There's a snake in my boot! — Peter",
    "I'm going to kill you, you fat bastard! — Stewie",
    "Ah! He said the word! — Peter",
    "To the Petercopter! — Peter",
    "To the Hindenpeter! — Peter",
    "I'm not fat, I'm just retaining water. — Peter",
    "Are you sure? — Brian",
    "I've got a golden ticket! — Peter",
    "Whoop-de-doo! — Lois",
    "I'm the king of the world! — Peter",
    "This is greater than the time I forgot how to sit down. — Peter",
    "Well, that's just fantastic. — Brian",
    "You're a big fat phony! — Phony Guy",
    "Hey, everyone! Look at the phony! — Phony Guy",
    "You're turning violet, Violet! — Peter",
    "I have a bad feeling about this. — Brian",
    "May the Force be with you. — Peter",
    "That's what she said. — Peter",
    "Where's my money? — Stewie",
    "You got money for fake mustaches but you don't got my money? — Stewie",
    "Clear list, clean slate, let's go. — Peter",
    "I'm holding out for a hero! — Brian",
    "Language, Timothy. — Lois",
    "I am the man with no name... Peter Griffin. — Peter",
    "Assahola-miah! — Peter",
    "I have a clip of it right here. — Peter",
    "You've got a lot to learn about this town, sweetie. — Peter",
    "Who's leg do I have to hump to get a martini around here? — Brian",
    "Let's go drink until we can't feel feelings anymore. — Peter",
    "Hey, ass-face! — Stewie",
    "Attention, shoppers. Outside the store is a giant chicken. — Tom Tucker",
    "I will destroy you! — Giant Chicken",
    "Why I oughta... — Peter",
    "You're a towel! — Peter",
    "Oh, right. The poison. The poison for Kuzco. — Peter",
    "Get out of my clean-cut community! — Mayor West",
    "I'm gonna go take a dump. — Peter",
    "You can't do that on television. — Peter",
    "My name is Consuela. — Consuela",
    "No... no... Superman no home. — Consuela",
    "Need more Lemon Pledge. — Consuela",
    "Come on, buddy, it's just a flesh wound. — Joe",
    "I can't feel my legs! — Joe",
    "Get to the chopper! — Peter",
    "I am the smart one, Chris is the dumb one, and Meg is the ugly one. — Stewie",
    "You're the worst pirate I've ever heard of. — Peter",
    "But you have heard of me. — Brian",
    "There's a giant chicken outside! — Peter",
    "Why are you wearing a tuxedo? It's after six. What am I, a farmer? — Peter",
    "I'm gonna go do some sweet jumps. — Chris",
    "You're a loose cannon, Griffin! — Principal Shepherd",
    "I don't think that's how it works. — Brian",
    "That's standard procedure. — Peter",
    "This is completely unacceptable. — Lois",
    "I can't believe you did that. — Lois",
    "I am a man of science. — Brian",
    "Go on, git! — Peter",
    "I hate you, I hate this house, and I hate my life! — Meg",
    "Oh, you're a big man with a gun! — Peter",
    "I'm not a cat, I'm a lawyer. — Brian",
    "This is the worst flight ever. — Quagmire",
    "I'm the backward-o man. — Peter",
    "I have a rendezvous with destiny. — Peter",
    "Shut your dirty mouth! — Lois",
    "You're not my dad! — Chris",
    "I am your father! — Peter",
    "You're a wizard, Peter. — Brian",
    "To the Peter-mobile! — Peter",
    "I'm going to the Clam. — Peter",
    "This is a total disaster. — Brian",
    "Everything is going according to plan. — Stewie",
    "I have the high ground! — Peter",
    "You were the chosen one! — Brian",
    "I look forward to our next encounter. — Stewie",
    "You can't escape me! — Giant Chicken",
    "I'll be back. — Peter",
    "What are you doing in my swamp? — Peter",
    "That's my purse! I don't know you! — Peter",
    "I'm going to give you a piece of my mind! — Lois",
    "You're a very naughty boy. — Lois",
    "I'm the king of the castle! — Peter",
    "This is completely ridiculous. — Brian",
    "I can't believe I ate the whole thing. — Peter",
    "You're out of order! — Peter",
    "The whole trial is out of order! — Peter",
    "I'm going to make you an offer you can't refuse. — Peter",
    "May the force be with you, always. — Brian",
    "I am your worst nightmare! — Peter",
    "You're a mean one, Mr. Grinch. — Peter",
    "I'm walking here! — Peter",
    "Show me the money! — Peter",
    "You had me at hello. — Peter",
    "Houston, we have a problem. — Brian",
    "There's no place like home. — Peter",
    "I'll have what she's having. — Peter",
    "You're gonna need a bigger boat. — Peter",
    "Here's looking at you, kid. — Brian",
    "Elementary, my dear Watson. — Brian",
    "I'm the master of my domain. — Peter",
    "That's gold, Jerry! Gold! — Peter",
    "No soup for you! — Peter",
    "Yada, yada, yada. — Lois"
  ];

  const random = lines[Math.floor(Math.random() * lines.length)];
  res.status(200).send(random);
}
