export default function handler(req, res) {
  const names = [
    "Dusty Dan – fired 3 shots and hit his own hat",
    "Deputy Fife – missed every single training target",
    "Rattlin’ Randy – once drew on a squirrel and lost",
    "Bolo Bill – thought the safety was fashion",
    "Clumsy Clint – trips over his own spurs",
    "Dizzy Desperado – spins more than shoots",
    "No-Scope Ned – aimed at the moon, hit his foot",
    "Triggerless Terry – still doesn't know how guns work",
    "Backfire Becky – got kicked by her own revolver",
    "Scattershot Sky – shoots like confetti",
    "Jam-Handed Jesse – permanently stuck in reload mode",
    "Lucky Misfire Lou – wins duels by the opponent laughing too hard",
    "Ricochet Ray – took out more signs than enemies",
    "Barrel Jam Billy – couldn’t shoot fish in a barrel",
    "Slamfire Sam – shoots first, regrets immediately",
    "Crossdraw Casey – accidentally drew their spoon",
    "Dust Cloud Darla – known for vanishing... not shooting",
    "Muzzle Muddle Morgan – pointed the wrong way. Again.",
    "Ten-Paces Pat – tripped on pace one",
    "Squintin’ Sawyer – can’t hit unless it’s yelling back",
    "Clickin’ Cassidy – dry fires like a champ",
    "Slippery Sloane – dropped their gun, twice",
    "Shootless Shane – brings a knife to a gunfight... and loses",
    "Boot Scoot Bailey – dances more than shoots",
    "Tin Badge Tobi – looks tough, can’t aim",
    "Tumbleweed Taylor – missed every moving target... including the tumbleweed",
    "Misfire Mags – feared only by inanimate objects",
    "Holster Drop Hank – fastest at disarming himself",
    "Whiffin' Wade – missed the saloon door from 5 feet",
    "Dryfire Dana – always forgets to load",
    "Spin-to-Win Wynn – dizzy before draw",
    "Screamin’ Sal – yells first, aims later",
    "Butterfingers Blake – drops more than they shoot",
    "Backpedal Barry – ran before the count of three",
    "Off-Sight Ollie – forgot which eye to aim with",
    "Clickbait Cal – makes noise, never hits",
    "Twitchin’ Toni – shakes like a cactus in the wind",
    "Latefire Lyle – always shoots after the dust settles",
    "Blank Round Robbie – never loaded the chamber",
    "Driftin’ Drew – aimed left, shot right",
    "Bangless Belle – her threats are louder than her bullets",
    "Bootheel Ben – scared of his own recoil",
    "Wanderin’ Walt – lost his gun. Again.",
    "Cactus Carl – points the wrong direction... consistently",
    "Trigger Ticklin’ Tilly – flinches before firing",
    "One-Shot Otis – only ever had one bullet... years ago",
    "Loose-Lipped Lane – talks more than hits",
    "Out-of-Sync Sid – always off by a second",
    "Flickshot Frankie – missed everything but the bartender",
    "Mildshot Mel – couldn’t hit a bell with a barrel",
    "Cross-Eye Cody – nobody knows where he’s aiming",
    "Granny-Grip Gwen – slowest draw in the West",
    "Plinkin’ Pete – ricochets guaranteed",
    "Rumble-Finger Remy – pulls trigger before thinking",
    "Lazy-Eye Eli – better at naps than shootouts",
    "Dustboot Dana – kicks more than clicks",
    "Whoopsie Willis – oops is their catchphrase",
    "Missin’ Mitch – 0 for 47 and counting",
    "Recoil Roxy – knocked down by her own gun",
    "Yellin’ Yancy – all bark, no bullseye",
    "False Start Freddy – draws too soon, shoots too late",
    "Trigger Delay Dana – always one moment behind",
    "Redundant Rick – shoots twice, misses twice",
    "Hiccup Hank – hiccups mid-aim every time",
    "Panic Fire Percy – empties the chamber in fear",
    "Jammed Jimmy – carries a decorative revolver",
    "Slowdraw Sal – still unholstering during the reload",
    "Dirty Dan – insists they’re the real one, but never proves it",
    "Pinhead Larry – no one knows what he’s aiming at, not even him",
    "The Bullet Whisperer – bullets refuse to listen [LEGENDARY]"
  ];

  const isRare = Math.random() < 0.05;
  const name = isRare
    ? names[names.length - 1]
    : names[Math.floor(Math.random() * (names.length - 1))];

  const user = req.query.user || "Stranger";
  const message = `@${user}, you shall now be known as... ${name}`;
  res.status(200).send(message);
}
