export default function handler(req, res) {
  const lines = [
    "🌲 South Park Wisdom 🌲 — 'Screw you guys, I'm going home.' — Cartman 🧢",
    "🎒 Kyle’s Thought of the Day: 'You know, I’ve learned something today…' 💬",
    "💩 Mr. Hankey just popped in to say: 'Howdy ho!' 🎄",
    "🛷 Stan's imagination: A world where adults make sense. 🚫",
    "🥩 Randy: 'I thought this was America!' — Imagination Level: 100 🇺🇸",
    "🎮 Cartman dreams of cheesy poofs and absolute power. 🧀👑",
    "🐻 Towelie: 'Don’t forget to bring a towel… or your creativity.' 🧠",
    "📉 Butters imagined being Professor Chaos. He still got grounded. 🧪",
    "🧠 Wendy’s brain is five seasons ahead. 📚",
    "🥴 Cartman: 'Respect my authoritah!' — now you’re imagining a dictatorship. 👮",
    "🎭 Kenny says something wise... we just can’t understand it. 🎤💀",
    "📺 TV says: 'You're watching Imaginationland News!' 📰",
    "🎄 Mr. Garrison imagines peace. His puppet disagrees. 🎭",
    "🍗 You just dreamed up Casa Bonita. Cartman is hiding in the closet. 🌮",
    "🎆 Kyle imagines a world without Cartman. It's peaceful. 🧘",
    "🌪️ Randy goes full chaos mode — again. 🍷🎤",
    "🔮 Imaginationland Portal activated! Welcome to the madness. ✨",
    "💂 British Cartman is here to narrate your imagination in a royal accent. 👑",
    "📚 South Park Elementary now offers a major in sarcasm. 🎓",
    "🛸 Aliens abduct your thoughts and give them back with ads. 👽",
    "🍁 Canada called. They want your imagination back, buddy. 🇨🇦",
    "💉 Mr. Mackey: 'Mmmkay, just imagine responsibly, mmmkay?' 🧠",
    "🧊 Kyle freezes Cartman in carbonite. Sweet dream. 🧊",
    "🕵️ Token starts a detective agency in your head. 🔍",
    "📼 Your thoughts are now a lost episode from season 6. 🎞️",
    "🎲 Cartman starts an imaginary board game. He still cheats. 🎲",
    "🍔 Chef returns in your mind to sing about chocolate salty... dreams. 🎶",
    "🧛 Goth kids wrote a poem in your head. It's very existential. 🖤",
    "🔥 Imaginationland caught fire. Blame it on Terrance and Phillip. 💨",
    "🪙 Kenny imagines a vending machine that never eats his coins. 💸",
    "📡 Cable Guy just disconnected your common sense. 📶",
    "📦 Amazon drone dropped off a bunch of chaos. Thanks, Cartman. 📦",
    "🎮 Your dreams are being streamed on Tegridy+ 📲",
    "🚬 Jimbo and Ned just imagined a war movie. Everyone exploded. 💣",
    "🏫 Mr. Garrison wrote a children’s book about your brain. It was banned. 📕",
    "🕊️ Butters thinks you're neat. His imagination is pure and slightly dangerous. 💖",
    "🍻 Randy: 'I'm not imagining, I'm just... festive!' 🍺",
    "🚽 You just imagined a toilet that screams 'TIMMY!' every flush. 🚽",
    "🎤 Cartman drops a rap album in your head. It’s all about snacks. 🍫",
    "🦠 You imagined COVID... oh wait, that already happened. 😷",
    "🧟 Imagination zombies ate your serious thoughts. Brains! 🧟",
    "💌 Token wrote you a song in his imagination. It slaps. 🎧",
    "📢 'You killed Kenny!' echoes in your brain forever. 💀",
    "📈 Cartman opened a stock portfolio in your dreams. It’s all in Dogecoin. 📉",
    "🛏️ Your thoughts just woke up next to Mr. Slave. 🌈",
    "🥼 Mr. Mackey imagined therapy. For your thoughts. Mmmkay. 🛋️",
    "🎮 Eric dreams of a future where he rules VR. And it's scary. 🎮",
    "🍦 Butters started an imaginary ice cream truck that only plays opera. 🍨",
    "💃 Randy starts a TikTok trend in your head. It’s embarrassing. 📱",
    "🦑 You just imagined a South Park anime. Cartman’s the villain. 💥",
    "📚 Kyle writes a thesis on ethical imagination. Cartman eats it. 📖"
  ];

  const random = lines[Math.floor(Math.random() * lines.length)];
  res.status(200).send(random);
}
